# From https://github.com/11ty/eleventy/discussions/1455#discussioncomment-6894194
name: Build and deploy 11ty to GH Pages

on:
  # trigger when something is pushed to the branch main
  push:
    branches: ["main"]
  # make it possible to trigger manually, useful for debugging
  workflow_dispatch: 

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies & build
        run: |
          npm install
          npx @11ty/eleventy
      - uses: actions/upload-pages-artifact@v4

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
